=== secondfoundation/Second-Foundation-Src/src/turk/src/interface/acpc_2010_server/GlassFrog/xsd/config.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            xmlns="urn:nonstandard:config" 
            targetNamespace="urn:nonstandard:config">

  <xsd:element name="Config" type="Config"/>

  <xsd:complexType name="Config">
    <xsd:sequence>
      <xsd:element name="Room" type="Room" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="BotList" type="BotList" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Room">
    <xsd:all>
      <xsd:element name="Name" type="xsd:string" minOccurs="1"/>
      <xsd:element name="Hands" type="xsd:positiveInteger" minOccurs="1"/>
      <xsd:element name="Gamedef" type="xsd:string" minOccurs="1"/>
      <xsd:element name="Seed" type="xsd:nonNegativeInteger" minOccurs="1"/>
    </xsd:all>
  </xsd:complexType>
  
  <xsd:complexType name="BotList">
    <xsd:sequence>
      <xsd:element name="Bot" type="Bot" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Bot">
    <xsd:all>
      <xsd:element name="Type" type="xsd:string" minOccurs="1"/>
      <xsd:element name="Name" type="xsd:string" minOccurs="1"/>
      <xsd:element name="BuyIn" type="xsd:positiveInteger" minOccurs="1"/>
      <xsd:element name="Location" type="xsd:string" minOccurs="1"/>
      <xsd:element name="Executable" type="xsd:string" minOccurs="1"/>
    </xsd:all>
  </xsd:complexType>

</xsd:schema>

=== secondfoundation/Second-Foundation-Src/src/turk/src/interface/acpc_2010_server/GlassFrog/config/SAMPLE_MATCH.confix.xml
<!-- A sample config file used to start a match.  This one will start a room 
     named SAMPLE with 500 hands using the 2 player limit gamedef and the seed
     for the cards of 12345.  It will have 2 bots, one one 127.0.0.1 with the 
     location of the executable being in the scripts/ directory in the server
     folder and the other will be on a remote machine with the executable being
     on the scratch drive
-->
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns="urn:nonstandard:config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nonstandard:config       file:xsd/config.xsd">
 <Room>
  <Name>
   SAMPLE
  </Name>
  <Hands>
   5000
  </Hands>
  <Gamedef>
   2Player.limit.gamedef.xml
  </Gamedef>
  <Seed>
   12345
  </Seed>
 </Room>

 <BotList>

  <Bot>
   <Type>
    AAAIPLAYER
   </Type>
   <Name>
    LocalChump
   </Name>
   <BuyIn>
    200
   </BuyIn>
   <Location>
    127.0.0.1
   </Location>
   <Executable>
    scripts/local_bot.sh
   </Executable>
  </Bot>

  <Bot>
   <Type>
    AAAIPLAYER
   </Type>
   <Name>
    RemoteChump
   </Name>
   <BuyIn>
    200
   </BuyIn>
   <Location>
    192.128.1.100
   </Location>
   <Executable>
    /local/scratch/remote_bot.sh
   </Executable>
  </Bot>

 </BotList>
</Config>
